add_library(interfaces STATIC
interfaces.hpp
task_interface/task_interface.hpp
task_interface/queue_interface.hpp
task_interface/mutex_interface.hpp

software_timer_interface/software_timer_interface.hpp
peripherals_base/spt_base.hpp
peripherals_base/spt_base.cpp

peripherals_base/communication_interface.hpp

peripherals_base/dio_interface.hpp
peripherals_base/iic_interface.hpp
peripherals_base/spi_interface.hpp
peripherals_base/uart_interface.hpp
)

target_link_libraries(interfaces PUBLIC commons)

target_include_directories(interfaces PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})